### ISSUE TITLE
Can we delete the master branch? no need for it right?, we are using the production branch

### ISSUE THREAD

**Issue by JakeLabate** [JakeLabate/BrandWield-Inc#48]

**Comment by weevil111** [comment]
@JakeLabate Yes. we can delete the master branch.

**Comment by JakeLabate** [comment]
@weevil111 Okay, plz do. Ty

**Comment by weevil111** [comment]
ok

**Comment by weevil111** [comment]
@JakeLabate I cannot delete master branch, because it is the default branch. You as a repository owner would have to change the default branch first.
Follow these simple steps to make production branch as the default branch:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch#changing-the-default-branch

**Comment by weevil111** [comment]
@JakeLabate Please follow the above steps and let me know once done. I'll delete the master branch after that
